In [1]:
import numpy as np
import numpy.random as random
import scipy as sp
from pandas import Series,DataFrame
import pandas as pd

# 可視化モジュール
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

# 小数第３まで表示
%precision 3

'%.3f'

In [3]:
# データの準備
# 等間隔の数字
smp_arr = np.arange(10)
print(smp_arr)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
# 元のデータ
print(smp_arr)

# 前から数字を5つ取得して、smp_arr_sliceに入れる
smp_arr_slice = smp_arr[0:5]
print(smp_arr_slice)

# smp_arr_sliceの3つめまでは10で置換
smp_arr_slice[0:3] = 10
print(smp_arr_slice)

# スライスを変更すると、オリジナルの変数の要素も変更されていることに注意
print(smp_arr)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[10 10 10  3  4]
[10 10 10  3  4  5  6  7  8  9]


# ブールインデックス参照

In [5]:
# オリジナルのデータを変更せずにコピーする場合は、以下のようにcopyを使う
smp_arr_copy = np.copy(smp_arr)

In [6]:
# データの準備
smp_names = np.array(['a', 'b', 'c', 'd', 'a'])
random.seed(0)
data = random.randn(5, 5)

print(smp_names)
print(data)

['a' 'b' 'c' 'd' 'a']
[[ 1.764  0.4    0.979  2.241  1.868]
 [-0.977  0.95  -0.151 -0.103  0.411]
 [ 0.144  1.454  0.761  0.122  0.444]
 [ 0.334  1.494 -0.205  0.313 -0.854]
 [-2.553  0.654  0.864 -0.742  2.27 ]]


In [10]:
# aに等しい箇所は True、そうでなければFalseになる
smp_names == 'a'

array([ True, False, False, False,  True], dtype=bool)

In [11]:
# np配列にbool値の配列を入れると、Trueに対応する箇所をするだけを抜き出せる
data[smp_names == 'a']

array([[ 1.764,  0.4  ,  0.979,  2.241,  1.868],
       [-2.553,  0.654,  0.864, -0.742,  2.27 ]])